// LOCALHOST

### GET ALL USERS
GET http://localhost:3000/user

### GET ALL DESTINATION
GET http://localhost:3000/destination

### POST DESTINATION
POST http://localhost:3000/destination HTTP/1.1
Content-Type: application/json

{
    "name": "2-Day Mompox Private Tour",
    "city": "Cartagena",
    "country": "Colombia",
    "description": "Discover the town's rich history, visit goldsmith workshops, and enjoy a scenic drive along the Magdalena River.",
    "tags": [
      "Exotic",
      "Caribbean"
    ],
    "rating": 0
}

### GET ALL REVIEWS
GET http://localhost:3000/review

### CREATE USER
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "username": "migarcos",
    "name": "Miguel",
    "email": "migarcos@email.com",
    "role": "developer",
    "password": "Mas97531!"
}

### CREATE REVIEW
POST http://localhost:3000/review HTTP/1.1
Content-Type: application/json

{
    "userId": "692b6c045e80369613bb7fa9",
    "destnationId": "692d11f1d971213cbda85416",
    "rating": 5,
    "reviewText": "A really exotic place, with beautiful enviroment. Kind people guides this tour",
    "visitDate": "2025-10-10",
    "reviewDate": "2025-10-15"
}

### CREATE REVIEW
POST http://localhost:3000/review HTTP/1.1
Content-Type: application/json

{
    "userId": "",
    "destnationId": "6927f199",
    "rating": 9,
    "reviewText": 98709870986096,
    "visitDate": "2025-01-02",
    "reviewDate": ""
}

### DELETE REVIEW
DELETE http://localhost:3000/review/692b54c1ca663498d7b4f9aa

### UPDATE REVIEW
PUT http://localhost:3000/review/692b54c1ca663498d7b4f9aa HTTP/1.1
Content-Type: application/json

{
    "rating": 5,
    "reviewText": "A fantastic experience visiting historical and industrial sites. I loved this wonderful, dreamlike trip."
}

